#配置config-server微服务



server:
  port: 8888
  
#配置git配置地址

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chihaojie2code/config-server-centre
  application:
    name: config-server
    
      