#服务提供者的端口号以9000开始
server:
  port: 9000
  
spring:
  application:
    name:   microservice-consume-movie-feign
    



#配置服务消费者
eureka:
  client:
   service-url:
       defaultZone: http://localhost:8761/eureka
      