server:
  port: 8761
  
spring:
  application:
    name:   eureka-server
    



#配置EurekaServer服务器
eureka:
  instance:
    hostname: discovery         # 指定该Eureka实例的主机名
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      