#服务提供者的端口号以9000开始
server:
  port: 9000
  
spring:
  application:
    name:   microservice-consume-movie
    



#配置服务消费者
eureka:
  client:
   register-with-eureka:  false  #我们这里搭建单点Eureka Server
   fetch-registry:  false
   service-url:
       defaultZone: http://localhost:8761/eureka
      